version: '3.8'
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/aima-db
      - TYPEORM_HOST=db
      - TYPEORM_PORT=5432
  db:
    image: postgres:13-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aima-db